language : java
jdk : openjdk11

branches:
  only : master

# Travis CI Server HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

notifications:
  email :
    recipients:
      - rlawngml59@gmail.com