language : java
jdk :
  - openjdk11

branches:
  only :
    - master

# Travis CI Server HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build -x test"

notifications:
  email :
    recipients:
      - rlawngml59@gmail.com

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/mungnyang.zip
#  - zip -r mungnyang *
#  - mkdir -p deploy
#  - mv mungnyang.zip deploy/mungnyang.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: mungnyang-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: mungnyang-springboot-build
    key: mungnyang.zip
    bundle_type: zip
    application: mungnyang
    deployment_group: mungnyang-group
    region: ap-northeast-2
    wait-until-deployed: true